---
- name: Install and configure Apache web server
  hosts: n01650117-c-vm-0.eastus.cloudapp.azure.com
  become: true

  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: present
      notify: Start Apache

    - name: Ensure Apache service is started
      systemd:
        name: httpd
        state: started

    - name: Create index.html if it does not exist
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add hostname to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hostname: {{ ansible_hostname }}"
      notify: Restart Apache

    - name: Enable Apache service to start on boot
      systemd:
        name: httpd
        enabled: true

  handlers:
    - name: Start Apache
      systemd:
        name: httpd
        state: started

    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted
