---
- name: Manage users and groups
  hosts: n01650117-c-vm-0.eastus.cloudapp.azure.com
  become: true
  vars:
    grouplist1: group10
    grouplist2: group20
    userlist1: user10
    userlist2: user20

  tasks:
    - name: Create group group10
      ansible.builtin.group:
        name: "{{ grouplist1 }}"
        state: present

    - name: Create group group20
      ansible.builtin.group:
        name: "{{ grouplist2 }}"
        state: present

    - name: Create user user10 with UID 1800 and supplementary membership to group10
      ansible.builtin.user:
        name: "{{ userlist1 }}"
        uid: 1800
        groups: "{{ grouplist1 }}"
        append: yes
        state: present

    - name: Create user user20 with UID 1900, shell /bin/bash, home directory /home/user20, and supplementary membership to group20
      ansible.builtin.user:
        name: "{{ userlist2 }}"
        uid: 1900
        shell: /bin/bash
        home: "/home/{{ userlist2 }}"
        groups: "{{ grouplist2 }}"
        append: yes
        state: present
