---
- name: User and Group Management, Software Installation
  hosts: linux
  become: true

  tasks:
    - name: Create group cloudadmins with GID 3000
      ansible.builtin.group:
        name: cloudadmins
        gid: 3000
        state: present

    - name: Create user account user4000 with UID 5000
      ansible.builtin.user:
        name: user4000
        uid: 5000
        state: present
        group: cloudadmins

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Install the latest version of nmap
      ansible.builtin.dnf:
        name: nmap
        state: latest

    - name: Ensure Apache service is started and enabled
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true
